export type Blog = {
  id: string;
  author_id: string;
  title: string;
  slug: string;
  excerpt: string;
  description: string;
  content: string;
  location: string;
  date: string;
  category: string;
  tags: string[];
  seo_description: string;
  image_url: string;
  images: string[];
  videos: string[];
  likes: number;
  status: string;
  created_at: string;
  updated_at: string;
};
